name: Cypress Tests

on:
  push:
    branches:
      - allure-report
      - develop

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.7.3'

      - name: Install dependencies
        run: npm install

      - name: Configurar JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Instalar Allure CLI
        run: |
          wget https://github.com/allure-framework/allure2/releases/latest/download/allure-2.21.0.tgz
          tar -zxvf allure-2.21.0.tgz
          sudo mv allure-2.21.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      - name: Verificar instalación de Allure
        run: allure --version

      - name: Limpiar directorio de reporte Allure
        run: npm run limpiar-reporte

      - name: Ejecutar pruebas de Cypress con Allure Adapter
        run: npm run ejecutar-pruebas

      - name: Listar resultados de Allure
        run: ls -la ./allure-results  # Verifica que hay archivos generados en allure-results

      - name: Generar reporte Allure como HTML estático
        run: allure generate ./allure-results --clean -o ./allure-report

      - name: Subir reporte Allure
        uses: actions/upload-artifact@v3
        with:
          name: Allure Report
          path: ./allure-report
          retention-days: 5
