name: Cypress Tests

on:
  push:
    branches:
      - allure-report
      - develop

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.7.3'

      - name: Install dependencies
        run: npm install

      - name: Clean Allure Report Directory
        run: npm run limpiar-reporte

      - name: Run Cypress Tests with Allure Adapter
        run: npm run ejecutar-pruebas

      - name: List Allure Results
        run: ls -la ./allure-results

      - name: Generate Allure Report as Static HTML
        run: allure generate ./allure-results --clean -o ./allure-report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: Allure Report
          path: ./allure-report
          retention-days: 5
