name: Cypress Tests

on:
  push:
    branches:
      - allure-report
      - develop

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Install Allure CLI via NPM
        run: npm install -g allure-commandline --save-dev

      - name: Verify Allure Installation
        run: allure --version

      - name: Clean Allure Report Directory
        run: npm run limpiar-reporte

      - name: Run Cypress Tests with Allure Adapter
        run: npm run ejecutar-pruebas

      - name: Generate Allure Report as Static HTML
        run: allure generate ./allure-results --clean -o ./allure-report

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
