name: Cypress Tests

on:
  push:
    branches:
      - allure-report
      - develop

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Install Allure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y allure

      - name: Clean Allure Report Directory
        run: npm run limpiar-reporte

      - name: Run Cypress Tests with Allure Adapter
        run: npm run ejecutar-pruebas

      - name: List Allure Results
        run: ls -la ./allure-results  # Verifica que hay archivos generados en allure-results

      - name: Ensure Allure Report Directory Exists
        run: mkdir -p ./allure-report

      - name: Generate Allure Report as Static HTML
        run: allure generate ./allure-results --clean -o ./allure-report || echo "Allure report generation failed"

      # Este paso siempre se ejecutará, incluso si los pasos anteriores fallan
      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Allure Report
          path: ./allure-report
          retention-days: 5
