name: Cypress Tests

on:
  push:
    branches:
      - main
      - develop

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js version 20 or newer
        uses: actions/setup-node@v3
        with:
          node-version: '>=20'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress Tests
        run: npx cypress run --reporter cypress-mochawesome-reporter --reporter-options reportDir=cypress/reports,reportFilename=index.html,overwrite=false,html=true

      - name: Upload HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: Cypress HTML Report
          path: ./cypress/reports/index.html
