name: Cypress Tests

on:
  push:
    branches:
      - allure-report
      - develop

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.7.3'

      - name: Install dependencies
        run: npm install

      - name: Instalar Allure CLI
        run: npm install -g allure-commandline --save-dev

      - name: Limpiar directorio de reporte Allure
        run: npm run limpiar-reporte

      - name: Ejecutar pruebas de Cypress con Allure Adapter
        run: npm run ejecutar-pruebas

      - name: Listar resultados de Allure
        run: ls -la ./allure-results

      - name: Generar reporte Allure como HTML estático
        run: allure generate ./allure-results --clean -o ./allure-report

      - name: Subir reporte Allure
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Allure Report
          path: ./allure-report
